package cmd

import (
	"errors"
	"os"
	"path/filepath"
	"testing"

	"github.com/steveyegge/gastown/internal/beads"
)

type fakeAgentBeadUpserter struct {
	gotID    string
	gotTitle string
	gotField *beads.AgentFields
	retErr   error
	calls    int
}

// CreateOrReopenAgentBead captures invocation details so tests can assert on
// the exact ID/title/fields generated by upsertCrewAgentBead.
func (f *fakeAgentBeadUpserter) CreateOrReopenAgentBead(id, title string, fields *beads.AgentFields) (*beads.Issue, error) {
	f.calls++
	f.gotID = id
	f.gotTitle = title
	f.gotField = fields
	if f.retErr != nil {
		return nil, f.retErr
	}
	return &beads.Issue{ID: id}, nil
}

func TestUpsertCrewAgentBead(t *testing.T) {
	townRoot := t.TempDir()
	if err := os.MkdirAll(filepath.Join(townRoot, ".beads"), 0755); err != nil {
		t.Fatalf("mkdir .beads: %v", err)
	}
	routes := `{"prefix":"bom-","path":"bti_ops_match"}` + "\n"
	if err := os.WriteFile(filepath.Join(townRoot, ".beads", "routes.jsonl"), []byte(routes), 0644); err != nil {
		t.Fatalf("write routes.jsonl: %v", err)
	}

	t.Run("uses create or reopen with canonical crew metadata", func(t *testing.T) {
		fake := &fakeAgentBeadUpserter{}
		id, err := upsertCrewAgentBead(fake, townRoot, "bti_ops_match", "neo")
		if err != nil {
			t.Fatalf("upsertCrewAgentBead: %v", err)
		}

		if fake.calls != 1 {
			t.Fatalf("CreateOrReopenAgentBead calls = %d, want 1", fake.calls)
		}
		if id != "bom-bti_ops_match-crew-neo" {
			t.Fatalf("returned id = %q, want %q", id, "bom-bti_ops_match-crew-neo")
		}
		if fake.gotID != id {
			t.Fatalf("upsert called with id %q, want %q", fake.gotID, id)
		}
		wantTitle := "Crew worker neo in bti_ops_match - human-managed persistent workspace."
		if fake.gotTitle != wantTitle {
			t.Fatalf("upsert title = %q, want %q", fake.gotTitle, wantTitle)
		}
		if fake.gotField == nil {
			t.Fatalf("upsert fields = nil, want non-nil")
		}
		if fake.gotField.RoleType != "crew" {
			t.Fatalf("RoleType = %q, want %q", fake.gotField.RoleType, "crew")
		}
		if fake.gotField.Rig != "bti_ops_match" {
			t.Fatalf("Rig = %q, want %q", fake.gotField.Rig, "bti_ops_match")
		}
		if fake.gotField.AgentState != "idle" {
			t.Fatalf("AgentState = %q, want %q", fake.gotField.AgentState, "idle")
		}
	})

	t.Run("propagates upsert errors", func(t *testing.T) {
		fake := &fakeAgentBeadUpserter{retErr: errors.New("boom")}
		id, err := upsertCrewAgentBead(fake, townRoot, "bti_ops_match", "neo")
		if err == nil {
			t.Fatalf("expected error, got nil")
		}
		if id != "" {
			t.Fatalf("id = %q, want empty on error", id)
		}
	})
}
